tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "sass/sass"
brew "composer"
brew "ruby", link: true
brew "yarn"
brew "sass/sass/sass"
cask "betterzip"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "suspicious-package"
cask "webpquicklook"
